# Linux with node install after for a lighter container
FROM alpine
RUN apk add --update nodejs npm

ENV ENVIRONMENT_MODE development

WORKDIR /root

# NPM install
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm ci

# Copy files
COPY ./tsconfig.json ./

EXPOSE 10500

CMD npm run start